# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSL2hd_ZrKkNEn1ZAOrr1D1569oQnobm
"""

import streamlit as st
import pandas as pd


#Caching the model for faster loading
@st.cache

st.write("Create Pencil Sketch of an Image")
st.header('Input any image')

st.file_uploader(label='upload image', type=['png', 'jpg'], accept_multiple_files=True, label_visibility="visible")

sketch= model.load_model('OpenCV_Pencil_sketch_from_image.ipynb')
st.write("Pencil Sketch of the image:", sketch)